---
version: "3"

services:
  3x-ui:
    #image: ghcr.io/mhsanaei/3x-ui:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 3x-ui
    hostname: my-3x-ui
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    tty: true
    network_mode: host
    restart: unless-stopped
